<?php
Tools::Autoload();
class MiscData{
	public $userDefaultQuickmenu = '
			[
			    { "Type": "Attribute", "Group": "GLOBAL", "Index": 13 },
				{ "Type": "Attribute", "Group": "GLOBAL", "Index": 16 },
				{ "Type": "Attribute", "Group": "GLOBAL", "Index": 17 },
				{ "Type": "Attribute", "Group": "GLOBAL", "Index": 0 },
				{ "Type": "Attribute", "Group": "GLOBAL", "Index": 15 },
				{ "Type": "Attribute", "Group": "GLOBAL", "Index": 12 },
				{ "Type": "Attribute", "Group": "GLOBAL", "Index": 8 },
				{ "Type": "Attribute", "Group": "GLOBAL", "Index": 11 },
				{ "Type": "Style", "Group": "Colors and Backgrounds", "Index": 6 },
				{ "Type": "Style", "Group": "Colors and Backgrounds", "Index": 23 },
				{ "Type": "Style", "Group": "Visual Formatting", "Index": 25 },
				{ "Type": "Style", "Group": "Visual Formatting", "Index": 7 },
				{ "Type": "Style", "Group": "Visual Formatting", "Index": 8 },
				{ "Type": "Style", "Group": "Visual Formatting", "Index": 29 },
				{ "Type": "Style", "Group": "Visual Formatting", "Index": 9 },
				{ "Type": "Style", "Group": "Visual Formatting", "Index": 30 },
				{ "Type": "Style", "Group": "Visual Formatting", "Index": 28 },
				{ "Type": "Style", "Group": "Visual Formatting", "Index": 14 },
			]';
	public $languages = array(
		'af'=>'Afrikaans',
		'af-za'=>'Afrikaans (South Africa)',
		'ar'=>'Arabic',
		'ar-ae'=>'Arabic (U.A.E.)',
		'ar-bh'=>'Arabic (Bahrain)',
		'ar-dz'=>'Arabic (Algeria)',
		'ar-eg'=>'Arabic (Egypt)',
		'ar-iq'=>'Arabic (Iraq)',
		'ar-jo'=>'Arabic (Jordan)',
		'ar-kw'=>'Arabic (Kuwait)',
		'ar-lb'=>'Arabic (Lebanon)',
		'ar-ly'=>'Arabic (Libya)',
		'ar-ma'=>'Arabic (Morocco)',
		'ar-om'=>'Arabic (Oman)',
		'ar-qa'=>'Arabic (Qatar)',
		'ar-sa'=>'Arabic (Saudi Arabia)',
		'ar-sy'=>'Arabic (Syria)',
		'ar-tn'=>'Arabic (Tunisia)',
		'ar-ye'=>'Arabic (Yemen)',
		'az'=>'Azeri (Latin)',
		'az-az'=>'Azeri (Cyrillic) (Azerbaijan)',
		'be'=>'Belarusian',
		'be-by'=>'Belarusian (Belarus)',
		'bg'=>'Bulgarian',
		'bg-bg'=>'Bulgarian (Bulgaria)',
		'bs-ba'=>'Bosnian (Bosnia and Herzegovina)',
		'ca'=>'Catalan',
		'ca-es'=>'Catalan (Spain)',
		'cs'=>'Czech',
		'cs-cz'=>'Czech (Czech Republic)',
		'cy'=>'Welsh',
		'cy-gb'=>'Welsh (United Kingdom)',
		'da'=>'Danish',
		'da-dk'=>'Danish (Denmark)',
		'de'=>'German',
		'de-at'=>'German (Austria)',
		'de-ch'=>'German (Switzerland)',
		'de-de'=>'German (Germany)',
		'de-li'=>'German (Liechtenstein)',
		'de-lu'=>'German (Luxembourg)',
		'dv'=>'Divehi',
		'dv-mv'=>'Divehi (Maldives)',
		'el'=>'Greek',
		'el-gr'=>'Greek (Greece)',
		'en'=>'English',
		'en-au'=>'English (Australia)',
		'en-bz'=>'English (Belize)',
		'en-ca'=>'English (Canada)',
		'en-cb'=>'English (Caribbean)',
		'en-gb'=>'English (United Kingdom)',
		'en-ie'=>'English (Ireland)',
		'en-jm'=>'English (Jamaica)',
		'en-nz'=>'English (New Zealand)',
		'en-ph'=>'English (Republic of the Philippines)',
		'en-tt'=>'English (Trinidad and Tobago)',
		'en-us'=>'English (United States)',
		'en-za'=>'English (South Africa)',
		'en-zw'=>'English (Zimbabwe)',
		'eo'=>'Esperanto',
		'es'=>'Spanish',
		'es-ar'=>'Spanish (Argentina)',
		'es-bo'=>'Spanish (Bolivia)',
		'es-cl'=>'Spanish (Chile)',
		'es-co'=>'Spanish (Colombia)',
		'es-cr'=>'Spanish (Costa Rica)',
		'es-do'=>'Spanish (Dominican Republic)',
		'es-ec'=>'Spanish (Ecuador)',
		'es-es'=>'Spanish (Spain)',
		'es-gt'=>'Spanish (Guatemala)',
		'es-hn'=>'Spanish (Honduras)',
		'es-mx'=>'Spanish (Mexico)',
		'es-ni'=>'Spanish (Nicaragua)',
		'es-pa'=>'Spanish (Panama)',
		'es-pe'=>'Spanish (Peru)',
		'es-pr'=>'Spanish (Puerto Rico)',
		'es-py'=>'Spanish (Paraguay)',
		'es-sv'=>'Spanish (El Salvador)',
		'es-uy'=>'Spanish (Uruguay)',
		'es-ve'=>'Spanish (Venezuela)',
		'et'=>'Estonian',
		'et-ee'=>'Estonian (Estonia)',
		'eu'=>'Basque',
		'eu-es'=>'Basque (Spain)',
		'fa'=>'Farsi',
		'fa-ir'=>'Farsi (Iran)',
		'fi'=>'Finnish',
		'fi-fi'=>'Finnish (Finland)',
		'fo'=>'Faroese',
		'fo-fo'=>'Faroese (Faroe Islands)',
		'fr'=>'French',
		'fr-be'=>'French (Belgium)',
		'fr-ca'=>'French (Canada)',
		'fr-ch'=>'French (Switzerland)',
		'fr-fr'=>'French (France)',
		'fr-lu'=>'French (Luxembourg)',
		'fr-mc'=>'French (Principality of Monaco)',
		'gl'=>'Galician',
		'gl-es'=>'Galician (Spain)',
		'gu'=>'Gujarati',
		'gu-in'=>'Gujarati (India)',
		'he'=>'Hebrew',
		'he-il'=>'Hebrew (Israel)',
		'hi'=>'Hindi',
		'hi-in'=>'Hindi (India)',
		'hr'=>'Croatian',
		'hr-ba'=>'Croatian (Bosnia and Herzegovina)',
		'hr-hr'=>'Croatian (Croatia)',
		'hu'=>'Hungarian',
		'hu-hu'=>'Hungarian (Hungary)',
		'hy'=>'Armenian',
		'hy-am'=>'Armenian (Armenia)',
		'id'=>'Indonesian',
		'id-id'=>'Indonesian (Indonesia)',
		'is'=>'Icelandic',
		'is-is'=>'Icelandic (Iceland)',
		'it'=>'Italian',
		'it-ch'=>'Italian (Switzerland)',
		'it-it'=>'Italian (Italy)',
		'ja'=>'Japanese',
		'ja-jp'=>'Japanese (Japan)',
		'ka'=>'Georgian',
		'ka-ge'=>'Georgian (Georgia)',
		'kk'=>'Kazakh',
		'kk-kz'=>'Kazakh (Kazakhstan)',
		'kn'=>'Kannada',
		'kn-in'=>'Kannada (India)',
		'ko'=>'Korean',
		'ko-kr'=>'Korean (Korea)',
		'kok'=>'Konkani',
		'kok-in'=>'Konkani (India)',
		'ky'=>'Kyrgyz',
		'ky-kg'=>'Kyrgyz (Kyrgyzstan)',
		'lt'=>'Lithuanian',
		'lt-lt'=>'Lithuanian (Lithuania)',
		'lv'=>'Latvian',
		'lv-lv'=>'Latvian (Latvia)',
		'mi'=>'Maori',
		'mi-nz'=>'Maori (New Zealand)',
		'mk'=>'FYRO Macedonian',
		'mn'=>'Mongolian',
		'mn-mn'=>'Mongolian (Mongolia)',
		'mr'=>'Marathi',
		'mr-in'=>'Marathi (India)',
		'ms'=>'Malay',
		'ms-bn'=>'Malay (Brunei Darussalam)',
		'ms-my'=>'Malay (Malaysia)',
		'mt'=>'Maltese',
		'mt-mt'=>'Maltese (Malta)',
		'nb'=>'Norwegian (Bokmål)',
		'nb-no'=>'Norwegian (Bokmål) (Norway)',
		'nl'=>'Dutch',
		'nl-be'=>'Dutch (Belgium)',
		'nl-nl'=>'Dutch (Netherlands)',
		'nn-no'=>'Norwegian (Nynorsk) (Norway)',
		'ns'=>'Northern Sotho',
		'ns-za'=>'Northern Sotho (South Africa)',
		'pa'=>'Punjabi',
		'pa-in'=>'Punjabi (India)',
		'pl'=>'Polish',
		'pl-pl'=>'Polish (Poland)',
		'ps'=>'Pashto',
		'ps-ar'=>'Pashto (Afghanistan)',
		'pt'=>'Portuguese',
		'pt-br'=>'Portuguese (Brazil)',
		'pt-pt'=>'Portuguese (Portugal)',
		'qu'=>'Quechua',
		'qu-bo'=>'Quechua (Bolivia)',
		'qu-ec'=>'Quechua (Ecuador)',
		'qu-pe'=>'Quechua (Peru)',
		'ro'=>'Romanian',
		'ro-ro'=>'Romanian (Romania)',
		'ru'=>'Russian',
		'ru-ru'=>'Russian (Russia)',
		'sa'=>'Sanskrit',
		'sa-in'=>'Sanskrit (India)',
		'se'=>'Sami (Northern)',
		'se-fi'=>'Sami (Finland)',
		'se-no'=>'Sami (Norway)',
		'se-se'=>'Sami (Sweden)',
		'sk'=>'Slovak',
		'sk-sk'=>'Slovak (Slovakia)',
		'sl'=>'Slovenian',
		'sl-si'=>'Slovenian (Slovenia)',
		'sq'=>'Albanian',
		'sq-al'=>'Albanian (Albania)',
		'sr-ba'=>'Serbian (Bosnia and Herzegovina)',
		'sr-sp'=>'Serbian (Serbia and Montenegro)',
		'sv'=>'Swedish',
		'sv-fi'=>'Swedish (Finland)',
		'sv-se'=>'Swedish (Sweden)',
		'sw'=>'Swahili',
		'sw-ke'=>'Swahili (Kenya)',
		'syr'=>'Syriac',
		'syr-sy'=>'Syriac (Syria)',
		'ta'=>'Tamil',
		'ta-in'=>'Tamil (India)',
		'te'=>'Telugu',
		'te-in'=>'Telugu (India)',
		'th'=>'Thai',
		'th-th'=>'Thai (Thailand)',
		'tl'=>'Tagalog',
		'tl-ph'=>'Tagalog (Philippines)',
		'tn'=>'Tswana',
		'tn-za'=>'Tswana (South Africa)',
		'tr'=>'Turkish',
		'tr-tr'=>'Turkish (Turkey)',
		'tt'=>'Tatar',
		'tt-ru'=>'Tatar (Russia)',
		'ts'=>'Tsonga',
		'uk'=>'Ukrainian',
		'uk-ua'=>'Ukrainian (Ukraine)',
		'ur'=>'Urdu',
		'ur-pk'=>'Urdu (Islamic Republic of Pakistan)',
		'uz'=>'Uzbek (Latin)',
		'uz-uz'=>'Uzbek (Uzbekistan)',
		'vi'=>'Vietnamese',
		'vi-vn'=>'Vietnamese (Viet Nam)',
		'xh'=>'Xhosa',
		'xh-za'=>'Xhosa (South Africa)',
		'zh'=>'Chinese',
		'zh-cn'=>'Chinese (S)',
		'zh-hk'=>'Chinese (Hong Kong)',
		'zh-mo'=>'Chinese (Macau)',
		'zh-sg'=>'Chinese (Singapore)',
		'zh-tw'=>'Chinese (T)',
		'zu'=>'Zulu',
		'zu-za'=>'Zulu (South Africa)'	);
	public $timezones = array(
	'Africa/Abidjan'=>'+00:00,+00:00',
	'Africa/Accra'=>'+00:00,+00:00',
	'Africa/Addis_Ababa'=>'+03:00,+03:00',
	'Africa/Algiers'=>'+01:00,+01:00',
	'Africa/Asmara'=>'+03:00,+03:00',
	'Africa/Bamako'=>'+00:00,+00:00',
	'Africa/Bangui'=>'+01:00,+01:00',
	'Africa/Banjul'=>'+00:00,+00:00',
	'Africa/Bissau'=>'+00:00,+00:00',
	'Africa/Blantyre'=>'+02:00,+02:00',
	'Africa/Brazzaville'=>'+01:00,+01:00',
	'Africa/Bujumbura'=>'+02:00,+02:00',
	'Africa/Cairo'=>'+02:00,+02:00',
	'Africa/Casablanca'=>'+01:00,+01:00',
	'Africa/Ceuta'=>'+01:00,+02:00',
	'Africa/Conakry'=>'+00:00,+00:00',
	'Africa/Dakar'=>'+00:00,+00:00',
	'Africa/Dar_es_Salaam'=>'+03:00,+03:00',
	'Africa/Djibouti'=>'+03:00,+03:00',
	'Africa/Douala'=>'+01:00,+01:00',
	'Africa/El_Aaiun'=>'+00:00,+01:00',
	'Africa/Freetown'=>'+00:00,+00:00',
	'Africa/Gaborone'=>'+02:00,+02:00',
	'Africa/Harare'=>'+02:00,+02:00',
	'Africa/Johannesburg'=>'+02:00,+02:00',
	'Africa/Juba'=>'+03:00,+03:00',
	'Africa/Kampala'=>'+03:00,+03:00',
	'Africa/Khartoum'=>'+02:00,+02:00',
	'Africa/Kigali'=>'+02:00,+02:00',
	'Africa/Kinshasa'=>'+01:00,+01:00',
	'Africa/Lagos'=>'+01:00,+01:00',
	'Africa/Libreville'=>'+01:00,+01:00',
	'Africa/Lome'=>'+00:00,+00:00',
	'Africa/Luanda'=>'+01:00,+01:00',
	'Africa/Lubumbashi'=>'+02:00,+02:00',
	'Africa/Lusaka'=>'+02:00,+02:00',
	'Africa/Malabo'=>'+01:00,+01:00',
	'Africa/Maputo'=>'+02:00,+02:00',
	'Africa/Maseru'=>'+02:00,+02:00',
	'Africa/Mbabane'=>'+02:00,+02:00',
	'Africa/Mogadishu'=>'+03:00,+03:00',
	'Africa/Monrovia'=>'+00:00,+00:00',
	'Africa/Nairobi'=>'+03:00,+03:00',
	'Africa/Ndjamena'=>'+01:00,+01:00',
	'Africa/Niamey'=>'+01:00,+01:00',
	'Africa/Nouakchott'=>'+00:00,+00:00',
	'Africa/Ouagadougou'=>'+00:00,+00:00',
	'Africa/Porto-Novo'=>'+01:00,+01:00',
	'Africa/Sao_Tome'=>'+00:00,+00:00',
	'Africa/Timbuktu'=>'+00:00,+00:00',
	'Africa/Tripoli'=>'+02:00,+02:00',
	'Africa/Tunis'=>'+01:00,+01:00',
	'Africa/Windhoek'=>'+02:00,+02:00',
	'America/Adak'=>'−10:00,−09:00',
	'America/Anchorage'=>'−09:00,−08:00',
	'America/Anguilla'=>'−04:00,−04:00',
	'America/Antigua'=>'−04:00,−04:00',
	'America/Araguaina'=>'−03:00,−03:00',
	'America/Argentina/Buenos_Aires'=>'−03:00,−03:00',
	'America/Argentina/Catamarca'=>'−03:00,−03:00',
	'America/Argentina/ComodRivadavia'=>'−03:00,−03:00',
	'America/Argentina/Cordoba'=>'−03:00,−03:00',
	'America/Argentina/Jujuy'=>'−03:00,−03:00',
	'America/Argentina/La_Rioja'=>'−03:00,−03:00',
	'America/Argentina/Mendoza'=>'−03:00,−03:00',
	'America/Argentina/Rio_Gallegos'=>'−03:00,−03:00',
	'America/Argentina/Salta'=>'−03:00,−03:00',
	'America/Argentina/San_Juan'=>'−03:00,−03:00',
	'America/Argentina/San_Luis'=>'−03:00,−03:00',
	'America/Argentina/Tucuman'=>'−03:00,−03:00',
	'America/Argentina/Ushuaia'=>'−03:00,−03:00',
	'America/Aruba'=>'−04:00,−04:00',
	'America/Asuncion'=>'−04:00,−03:00',
	'America/Atikokan'=>'−05:00,−05:00',
	'America/Atka'=>'−10:00,−09:00',
	'America/Bahia'=>'−03:00,−03:00',
	'America/Bahia_Banderas'=>'−06:00,−05:00',
	'America/Barbados'=>'−04:00,−04:00',
	'America/Belem'=>'−03:00,−03:00',
	'America/Belize'=>'−06:00,−06:00',
	'America/Blanc-Sablon'=>'−04:00,−04:00',
	'America/Boa_Vista'=>'−04:00,−04:00',
	'America/Bogota'=>'−05:00,−05:00',
	'America/Boise'=>'−07:00,−06:00',
	'America/Buenos_Aires'=>'−03:00,−03:00',
	'America/Cambridge_Bay'=>'−07:00,−06:00',
	'America/Campo_Grande'=>'−04:00,−03:00',
	'America/Cancun'=>'−05:00,−05:00',
	'America/Caracas'=>'−04:00,−04:00',
	'America/Catamarca'=>'−03:00,−03:00',
	'America/Cayenne'=>'−03:00,−03:00',
	'America/Cayman'=>'−05:00,−05:00',
	'America/Chicago'=>'−06:00,−05:00',
	'America/Chihuahua'=>'−07:00,−06:00',
	'America/Coral_Harbour'=>'−05:00,−05:00',
	'America/Cordoba'=>'−03:00,−03:00',
	'America/Costa_Rica'=>'−06:00,−06:00',
	'America/Creston'=>'−07:00,−07:00',
	'America/Cuiaba'=>'−04:00,−03:00',
	'America/Curacao'=>'−04:00,−04:00',
	'America/Danmarkshavn'=>'+00:00,+00:00',
	'America/Dawson'=>'−08:00,−07:00',
	'America/Dawson_Creek'=>'−07:00,−07:00',
	'America/Denver'=>'−07:00,−06:00',
	'America/Detroit'=>'−05:00,−04:00',
	'America/Dominica'=>'−04:00,−04:00',
	'America/Edmonton'=>'−07:00,−06:00',
	'America/Eirunepe'=>'−05:00,−05:00',
	'America/El_Salvador'=>'−06:00,−06:00',
	'America/Ensenada'=>'−08:00,−07:00',
	'America/Fort_Nelson'=>'−07:00,−07:00',
	'America/Fort_Wayne'=>'−05:00,−04:00',
	'America/Fortaleza'=>'−03:00,−03:00',
	'America/Glace_Bay'=>'−04:00,−03:00',
	'America/Godthab'=>'−03:00,−02:00',
	'America/Goose_Bay'=>'−04:00,−03:00',
	'America/Grand_Turk'=>'−05:00,−04:00',
	'America/Grenada'=>'−04:00,−04:00',
	'America/Guadeloupe'=>'−04:00,−04:00',
	'America/Guatemala'=>'−06:00,−06:00',
	'America/Guayaquil'=>'−05:00,−05:00',
	'America/Guyana'=>'−04:00,−04:00',
	'America/Halifax'=>'−04:00,−03:00',
	'America/Havana'=>'−05:00,−04:00',
	'America/Hermosillo'=>'−07:00,−07:00',
	'America/Indiana/Indianapolis'=>'−05:00,−04:00',
	'America/Indiana/Knox'=>'−06:00,−05:00',
	'America/Indiana/Marengo'=>'−05:00,−04:00',
	'America/Indiana/Petersburg'=>'−05:00,−04:00',
	'America/Indiana/Tell_City'=>'−06:00,−05:00',
	'America/Indiana/Vevay'=>'−05:00,−04:00',
	'America/Indiana/Vincennes'=>'−05:00,−04:00',
	'America/Indiana/Winamac'=>'−05:00,−04:00',
	'America/Indianapolis'=>'−05:00,−04:00',
	'America/Inuvik'=>'−07:00,−06:00',
	'America/Iqaluit'=>'−05:00,−04:00',
	'America/Jamaica'=>'−05:00,−05:00',
	'America/Jujuy'=>'−03:00,−03:00',
	'America/Juneau'=>'−09:00,−08:00',
	'America/Kentucky/Louisville'=>'−05:00,−04:00',
	'America/Kentucky/Monticello'=>'−05:00,−04:00',
	'America/Knox_IN'=>'−06:00,−05:00',
	'America/Kralendijk'=>'−04:00,−04:00',
	'America/La_Paz'=>'−04:00,−04:00',
	'America/Lima'=>'−05:00,−05:00',
	'America/Los_Angeles'=>'−08:00,−07:00',
	'America/Louisville'=>'−05:00,−04:00',
	'America/Lower_Princes'=>'−04:00,−04:00',
	'America/Maceio'=>'−03:00,−03:00',
	'America/Managua'=>'−06:00,−06:00',
	'America/Manaus'=>'−04:00,−04:00',
	'America/Marigot'=>'−04:00,−04:00',
	'America/Martinique'=>'−04:00,−04:00',
	'America/Matamoros'=>'−06:00,−05:00',
	'America/Mazatlan'=>'−07:00,−06:00',
	'America/Mendoza'=>'−03:00,−03:00',
	'America/Menominee'=>'−06:00,−05:00',
	'America/Merida'=>'−06:00,−05:00',
	'America/Metlakatla'=>'−09:00,−08:00',
	'America/Mexico_City'=>'−06:00,−05:00',
	'America/Miquelon'=>'−03:00,−02:00',
	'America/Moncton'=>'−04:00,−03:00',
	'America/Monterrey'=>'−06:00,−05:00',
	'America/Montevideo'=>'−03:00,−03:00',
	'America/Montreal'=>'−05:00,−04:00',
	'America/Montserrat'=>'−04:00,−04:00',
	'America/Nassau'=>'−05:00,−04:00',
	'America/New_York'=>'−05:00,−04:00',
	'America/Nipigon'=>'−05:00,−04:00',
	'America/Nome'=>'−09:00,−08:00',
	'America/Noronha'=>'−02:00,−02:00',
	'America/North_Dakota/Beulah'=>'−06:00,−05:00',
	'America/North_Dakota/Center'=>'−06:00,−05:00',
	'America/North_Dakota/New_Salem'=>'−06:00,−05:00',
	'America/Ojinaga'=>'−07:00,−06:00',
	'America/Panama'=>'−05:00,−05:00',
	'America/Pangnirtung'=>'−05:00,−04:00',
	'America/Paramaribo'=>'−03:00,−03:00',
	'America/Phoenix'=>'−07:00,−07:00',
	'America/Port_of_Spain'=>'−04:00,−04:00',
	'America/Port-au-Prince'=>'−05:00,−04:00',
	'America/Porto_Acre'=>'−05:00,−05:00',
	'America/Porto_Velho'=>'−04:00,−04:00',
	'America/Puerto_Rico'=>'−04:00,−04:00',
	'America/Punta_Arenas'=>'−03:00,−03:00',
	'America/Rainy_River'=>'−06:00,−05:00',
	'America/Rankin_Inlet'=>'−06:00,−05:00',
	'America/Recife'=>'−03:00,−03:00',
	'America/Regina'=>'−06:00,−06:00',
	'America/Resolute'=>'−06:00,−05:00',
	'America/Rio_Branco'=>'−05:00,−05:00',
	'America/Rosario'=>'−03:00,−03:00',
	'America/Santa_Isabel'=>'−08:00,−07:00',
	'America/Santarem'=>'−03:00,−03:00',
	'America/Santiago'=>'−04:00,−03:00',
	'America/Santo_Domingo'=>'−04:00,−04:00',
	'America/Sao_Paulo'=>'−03:00,−02:00',
	'America/Scoresbysund'=>'−01:00,+00:00',
	'America/Shiprock'=>'−07:00,−06:00',
	'America/Sitka'=>'−09:00,−08:00',
	'America/St_Barthelemy'=>'−04:00,−04:00',
	'America/St_Johns'=>'−03:30,−02:30',
	'America/St_Kitts'=>'−04:00,−04:00',
	'America/St_Lucia'=>'−04:00,−04:00',
	'America/St_Thomas'=>'−04:00,−04:00',
	'America/St_Vincent'=>'−04:00,−04:00',
	'America/Swift_Current'=>'−06:00,−06:00',
	'America/Tegucigalpa'=>'−06:00,−06:00',
	'America/Thule'=>'−04:00,−03:00',
	'America/Thunder_Bay'=>'−05:00,−04:00',
	'America/Tijuana'=>'−08:00,−07:00',
	'America/Toronto'=>'−05:00,−04:00',
	'America/Tortola'=>'−04:00,−04:00',
	'America/Vancouver'=>'−08:00,−07:00',
	'America/Virgin'=>'−04:00,−04:00',
	'America/Whitehorse'=>'−08:00,−07:00',
	'America/Winnipeg'=>'−06:00,−05:00',
	'America/Yakutat'=>'−09:00,−08:00',
	'America/Yellowknife'=>'−07:00,−06:00',
	'Antarctica/Casey'=>'+11:00,+11:00',
	'Antarctica/Davis'=>'+07:00,+07:00',
	'Antarctica/DumontDUrville'=>'+10:00,+10:00',
	'Antarctica/Macquarie'=>'+11:00,+11:00',
	'Antarctica/Mawson'=>'+05:00,+05:00',
	'Antarctica/McMurdo'=>'+12:00,+13:00',
	'Antarctica/Palmer'=>'−03:00,−03:00',
	'Antarctica/Rothera'=>'−03:00,−03:00',
	'Antarctica/South_Pole'=>'+12:00,+13:00',
	'Antarctica/Syowa'=>'+03:00,+03:00',
	'Antarctica/Troll'=>'+00:00,+02:00',
	'Antarctica/Vostok'=>'+06:00,+06:00',
	'Arctic/Longyearbyen'=>'+01:00,+02:00',
	'Asia/Aden'=>'+03:00,+03:00',
	'Asia/Almaty'=>'+06:00,+06:00',
	'Asia/Amman'=>'+02:00,+03:00',
	'Asia/Anadyr'=>'+12:00,+12:00',
	'Asia/Aqtau'=>'+05:00,+05:00',
	'Asia/Aqtobe'=>'+05:00,+05:00',
	'Asia/Ashgabat'=>'+05:00,+05:00',
	'Asia/Ashkhabad'=>'+05:00,+05:00',
	'Asia/Atyrau'=>'+05:00,+05:00',
	'Asia/Baghdad'=>'+03:00,+03:00',
	'Asia/Bahrain'=>'+03:00,+03:00',
	'Asia/Baku'=>'+04:00,+04:00',
	'Asia/Bangkok'=>'+07:00,+07:00',
	'Asia/Barnaul'=>'+07:00,+07:00',
	'Asia/Beirut'=>'+02:00,+03:00',
	'Asia/Bishkek'=>'+06:00,+06:00',
	'Asia/Brunei'=>'+08:00,+08:00',
	'Asia/Calcutta'=>'+05:30,+05:30',
	'Asia/Chita'=>'+09:00,+09:00',
	'Asia/Choibalsan'=>'+08:00,+08:00',
	'Asia/Chongqing'=>'+08:00,+08:00',
	'Asia/Chungking'=>'+08:00,+08:00',
	'Asia/Colombo'=>'+05:30,+05:30',
	'Asia/Dacca'=>'+06:00,+06:00',
	'Asia/Damascus'=>'+02:00,+03:00',
	'Asia/Dhaka'=>'+06:00,+06:00',
	'Asia/Dili'=>'+09:00,+09:00',
	'Asia/Dubai'=>'+04:00,+04:00',
	'Asia/Dushanbe'=>'+05:00,+05:00',
	'Asia/Famagusta'=>'+02:00,+02:00',
	'Asia/Gaza'=>'+02:00,+03:00',
	'Asia/Harbin'=>'+08:00,+08:00',
	'Asia/Hebron'=>'+02:00,+03:00',
	'Asia/Ho_Chi_Minh'=>'+07:00,+07:00',
	'Asia/Hong_Kong'=>'+08:00,+08:00',
	'Asia/Hovd'=>'+07:00,+07:00',
	'Asia/Irkutsk'=>'+08:00,+08:00',
	'Asia/Istanbul'=>'+03:00,+03:00',
	'Asia/Jakarta'=>'+07:00,+07:00',
	'Asia/Jayapura'=>'+09:00,+09:00',
	'Asia/Jerusalem'=>'+02:00,+03:00',
	'Asia/Kabul'=>'+04:30,+04:30',
	'Asia/Kamchatka'=>'+12:00,+12:00',
	'Asia/Karachi'=>'+05:00,+05:00',
	'Asia/Kashgar'=>'+06:00,+06:00',
	'Asia/Kathmandu'=>'+05:45,+05:45',
	'Asia/Katmandu'=>'+05:45,+05:45',
	'Asia/Khandyga'=>'+09:00,+09:00',
	'Asia/Kolkata'=>'+05:30,+05:30',
	'Asia/Krasnoyarsk'=>'+07:00,+07:00',
	'Asia/Kuala_Lumpur'=>'+08:00,+08:00',
	'Asia/Kuching'=>'+08:00,+08:00',
	'Asia/Kuwait'=>'+03:00,+03:00',
	'Asia/Macao'=>'+08:00,+08:00',
	'Asia/Macau'=>'+08:00,+08:00',
	'Asia/Magadan'=>'+11:00,+11:00',
	'Asia/Makassar'=>'+08:00,+08:00',
	'Asia/Manila'=>'+08:00,+08:00',
	'Asia/Muscat'=>'+04:00,+04:00',
	'Asia/Novokuznetsk'=>'+07:00,+07:00',
	'Asia/Novosibirsk'=>'+07:00,+07:00',
	'Asia/Omsk'=>'+06:00,+06:00',
	'Asia/Oral'=>'+05:00,+05:00',
	'Asia/Phnom_Penh'=>'+07:00,+07:00',
	'Asia/Pontianak'=>'+07:00,+07:00',
	'Asia/Pyongyang'=>'+09:00,+09:00',
	'Asia/Qatar'=>'+03:00,+03:00',
	'Asia/Qyzylorda'=>'+05:00,+05:00',
	'Asia/Rangoon'=>'+06:30,+06:30',
	'Asia/Riyadh'=>'+03:00,+03:00',
	'Asia/Saigon'=>'+07:00,+07:00',
	'Asia/Sakhalin'=>'+11:00,+11:00',
	'Asia/Samarkand'=>'+05:00,+05:00',
	'Asia/Seoul'=>'+09:00,+09:00',
	'Asia/Shanghai'=>'+08:00,+08:00',
	'Asia/Singapore'=>'+08:00,+08:00',
	'Asia/Srednekolymsk'=>'+11:00,+11:00',
	'Asia/Taipei'=>'+08:00,+08:00',
	'Asia/Tashkent'=>'+05:00,+05:00',
	'Asia/Tbilisi'=>'+04:00,+04:00',
	'Asia/Tehran'=>'+03:30,+04:30',
	'Asia/Tel_Aviv'=>'+02:00,+03:00',
	'Asia/Thimbu'=>'+06:00,+06:00',
	'Asia/Thimphu'=>'+06:00,+06:00',
	'Asia/Tokyo'=>'+09:00,+09:00',
	'Asia/Tomsk'=>'+07:00,+07:00',
	'Asia/Ujung_Pandang'=>'+08:00,+08:00',
	'Asia/Ulaanbaatar'=>'+08:00,+08:00',
	'Asia/Ulan_Bator'=>'+08:00,+08:00',
	'Asia/Urumqi'=>'+06:00,+06:00',
	'Asia/Ust-Nera'=>'+10:00,+10:00',
	'Asia/Vientiane'=>'+07:00,+07:00',
	'Asia/Vladivostok'=>'+10:00,+10:00',
	'Asia/Yakutsk'=>'+09:00,+09:00',
	'Asia/Yangon'=>'+06:30,+06:30',
	'Asia/Yekaterinburg'=>'+05:00,+05:00',
	'Asia/Yerevan'=>'+04:00,+04:00',
	'Atlantic/Azores'=>'−01:00,+00:00',
	'Atlantic/Bermuda'=>'−04:00,−03:00',
	'Atlantic/Canary'=>'+00:00,+01:00',
	'Atlantic/Cape_Verde'=>'−01:00,−01:00',
	'Atlantic/Faeroe'=>'+00:00,+01:00',
	'Atlantic/Faroe'=>'+00:00,+01:00',
	'Atlantic/Jan_Mayen'=>'+01:00,+02:00',
	'Atlantic/Madeira'=>'+00:00,+01:00',
	'Atlantic/Reykjavik'=>'+00:00,+00:00',
	'Atlantic/South_Georgia'=>'−02:00,−02:00',
	'Atlantic/St_Helena'=>'+00:00,+00:00',
	'Atlantic/Stanley'=>'−03:00,−03:00',
	'Australia/Adelaide'=>'+09:30,+10:30',
	'Australia/Brisbane'=>'+10:00,+10:00',
	'Australia/Broken_Hill'=>'+09:30,+10:30',
	'Australia/Canberra'=>'+10:00,+11:00',
	'Australia/Currie'=>'+10:00,+11:00',
	'Australia/Darwin'=>'+09:30,+09:30',
	'Australia/Eucla'=>'+08:45,+08:45',
	'Australia/Hobart'=>'+10:00,+11:00',
	'Australia/Lindeman'=>'+10:00,+10:00',
	'Australia/Lord_Howe'=>'+10:30,+11:00',
	'Australia/Melbourne'=>'+10:00,+11:00',
	'Australia/Perth'=>'+08:00,+08:00',
	'Australia/Sydney'=>'+10:00,+11:00',
	'Australia/Yancowinna'=>'+09:30,+10:30',
	'Etc/GMT'=>'+00:00,+00:00',
	'Etc/GMT+0'=>'+00:00,+00:00',
	'Etc/GMT+1'=>'−01:00,−01:00',
	'Etc/GMT+10'=>'−10:00,−10:00',
	'Etc/GMT+11'=>'−11:00,−11:00',
	'Etc/GMT+12'=>'−12:00,−12:00',
	'Etc/GMT+2'=>'−02:00,−02:00',
	'Etc/GMT+3'=>'−03:00,−03:00',
	'Etc/GMT+4'=>'−04:00,−04:00',
	'Etc/GMT+5'=>'−05:00,−05:00',
	'Etc/GMT+6'=>'−06:00,−06:00',
	'Etc/GMT+7'=>'−07:00,−07:00',
	'Etc/GMT+8'=>'−08:00,−08:00',
	'Etc/GMT+9'=>'−09:00,−09:00',
	'Etc/GMT0'=>'+00:00,+00:00',
	'Etc/GMT-0'=>'+00:00,+00:00',
	'Etc/GMT-1'=>'+01:00,+01:00',
	'Etc/GMT-10'=>'+10:00,+10:00',
	'Etc/GMT-11'=>'+11:00,+11:00',
	'Etc/GMT-12'=>'+12:00,+12:00',
	'Etc/GMT-13'=>'+13:00,+13:00',
	'Etc/GMT-14'=>'+14:00,+14:00',
	'Etc/GMT-2'=>'+02:00,+02:00',
	'Etc/GMT-3'=>'+03:00,+03:00',
	'Etc/GMT-4'=>'+04:00,+04:00',
	'Etc/GMT-5'=>'+05:00,+05:00',
	'Etc/GMT-6'=>'+06:00,+06:00',
	'Etc/GMT-7'=>'+07:00,+07:00',
	'Etc/GMT-8'=>'+08:00,+08:00',
	'Etc/GMT-9'=>'+09:00,+09:00',
	'Etc/UTC'=>'+00:00,+00:00',
	'Europe/Amsterdam'=>'+01:00,+02:00',
	'Europe/Andorra'=>'+01:00,+02:00',
	'Europe/Astrakhan'=>'+04:00,+04:00',
	'Europe/Athens'=>'+02:00,+03:00',
	'Europe/Belfast'=>'+00:00,+01:00',
	'Europe/Belgrade'=>'+01:00,+02:00',
	'Europe/Berlin'=>'+01:00,+02:00',
	'Europe/Bratislava'=>'+01:00,+02:00',
	'Europe/Brussels'=>'+01:00,+02:00',
	'Europe/Bucharest'=>'+02:00,+03:00',
	'Europe/Budapest'=>'+01:00,+02:00',
	'Europe/Busingen'=>'+01:00,+02:00',
	'Europe/Chisinau'=>'+02:00,+03:00',
	'Europe/Copenhagen'=>'+01:00,+02:00',
	'Europe/Dublin'=>'+00:00,+01:00',
	'Europe/Gibraltar'=>'+01:00,+02:00',
	'Europe/Guernsey'=>'+00:00,+01:00',
	'Europe/Helsinki'=>'+02:00,+03:00',
	'Europe/Isle_of_Man'=>'+00:00,+01:00',
	'Europe/Istanbul'=>'+03:00,+03:00',
	'Europe/Jersey'=>'+00:00,+01:00',
	'Europe/Kaliningrad'=>'+02:00,+02:00',
	'Europe/Kiev'=>'+02:00,+03:00',
	'Europe/Kirov'=>'+03:00,+03:00',
	'Europe/Lisbon'=>'+00:00,+01:00',
	'Europe/Ljubljana'=>'+01:00,+02:00',
	'Europe/London'=>'+00:00,+01:00',
	'Europe/Luxembourg'=>'+01:00,+02:00',
	'Europe/Madrid'=>'+01:00,+02:00',
	'Europe/Malta'=>'+01:00,+02:00',
	'Europe/Mariehamn'=>'+02:00,+03:00',
	'Europe/Minsk'=>'+03:00,+03:00',
	'Europe/Monaco'=>'+01:00,+02:00',
	'Europe/Moscow'=>'+03:00,+03:00',
	'Asia/Nicosia'=>'+02:00,+03:00',
	'Europe/Oslo'=>'+01:00,+02:00',
	'Europe/Paris'=>'+01:00,+02:00',
	'Europe/Podgorica'=>'+01:00,+02:00',
	'Europe/Prague'=>'+01:00,+02:00',
	'Europe/Riga'=>'+02:00,+03:00',
	'Europe/Rome'=>'+01:00,+02:00',
	'Europe/Samara'=>'+04:00,+04:00',
	'Europe/San_Marino'=>'+01:00,+02:00',
	'Europe/Sarajevo'=>'+01:00,+02:00',
	'Europe/Saratov'=>'+04:00,+04:00',
	'Europe/Simferopol'=>'+03:00,+03:00',
	'Europe/Skopje'=>'+01:00,+02:00',
	'Europe/Sofia'=>'+02:00,+03:00',
	'Europe/Stockholm'=>'+01:00,+02:00',
	'Europe/Tallinn'=>'+02:00,+03:00',
	'Europe/Tirane'=>'+01:00,+02:00',
	'Europe/Tiraspol'=>'+02:00,+03:00',
	'Europe/Ulyanovsk'=>'+04:00,+04:00',
	'Europe/Uzhgorod'=>'+02:00,+03:00',
	'Europe/Vaduz'=>'+01:00,+02:00',
	'Europe/Vatican'=>'+01:00,+02:00',
	'Europe/Vienna'=>'+01:00,+02:00',
	'Europe/Vilnius'=>'+02:00,+03:00',
	'Europe/Volgograd'=>'+04:00,+04:00',
	'Europe/Warsaw'=>'+02:00,+03:00',
	'Europe/Zagreb'=>'+01:00,+02:00',
	'Europe/Zaporozhye'=>'+02:00,+03:00',
	'Europe/Zurich'=>'+01:00,+02:00',
	'GMT'=>'+00:00,+00:00',
	'Indian/Antananarivo'=>'+03:00,+03:00',
	'Indian/Chagos'=>'+06:00,+06:00',
	'Indian/Christmas'=>'+07:00,+07:00',
	'Indian/Cocos'=>'+06:30,+06:30',
	'Indian/Comoro'=>'+03:00,+03:00',
	'Indian/Kerguelen'=>'+05:00,+05:00',
	'Indian/Mahe'=>'+04:00,+04:00',
	'Indian/Maldives'=>'+05:00,+05:00',
	'Indian/Mauritius'=>'+04:00,+04:00',
	'Indian/Mayotte'=>'+03:00,+03:00',
	'Indian/Reunion'=>'+04:00,+04:00',
	'Pacific/Apia'=>'+13:00,+14:00',
	'Pacific/Auckland'=>'+12:00,+13:00',
	'Pacific/Bougainville'=>'+11:00,+11:00',
	'Pacific/Chatham'=>'+12:45,+13:45',
	'Pacific/Chuuk'=>'+10:00,+10:00',
	'Pacific/Easter'=>'−06:00,−05:00',
	'Pacific/Efate'=>'+11:00,+11:00',
	'Pacific/Enderbury'=>'+13:00,+13:00',
	'Pacific/Fakaofo'=>'+13:00,+13:00',
	'Pacific/Fiji'=>'+12:00,+13:00',
	'Pacific/Funafuti'=>'+12:00,+12:00',
	'Pacific/Galapagos'=>'−06:00,−06:00',
	'Pacific/Gambier'=>'−09:00,−09:00',
	'Pacific/Guadalcanal'=>'+11:00,+11:00',
	'Pacific/Guam'=>'+10:00,+10:00',
	'Pacific/Honolulu'=>'−10:00,−10:00',
	'Pacific/Johnston'=>'−10:00,−10:00',
	'Pacific/Kiritimati'=>'+14:00,+14:00',
	'Pacific/Kosrae'=>'+11:00,+11:00',
	'Pacific/Kwajalein'=>'+12:00,+12:00',
	'Pacific/Majuro'=>'+12:00,+12:00',
	'Pacific/Marquesas'=>'−09:30,−09:30',
	'Pacific/Midway'=>'−11:00,−11:00',
	'Pacific/Nauru'=>'+12:00,+12:00',
	'Pacific/Niue'=>'−11:00,−11:00',
	'Pacific/Norfolk'=>'+11:00,+11:00',
	'Pacific/Noumea'=>'+11:00,+11:00',
	'Pacific/Pago_Pago'=>'−11:00,−11:00',
	'Pacific/Palau'=>'+09:00,+09:00',
	'Pacific/Pitcairn'=>'−08:00,−08:00',
	'Pacific/Pohnpei'=>'+11:00,+11:00',
	'Pacific/Ponape'=>'+11:00,+11:00',
	'Pacific/Port_Moresby'=>'+10:00,+10:00',
	'Pacific/Rarotonga'=>'−10:00,−10:00',
	'Pacific/Saipan'=>'+10:00,+10:00',
	'Pacific/Samoa'=>'−11:00,−11:00',
	'Pacific/Tahiti'=>'−10:00,−10:00',
	'Pacific/Tarawa'=>'+12:00,+12:00',
	'Pacific/Tongatapu'=>'+13:00,+14:00',
	'Pacific/Truk'=>'+10:00,+10:00',
	'Pacific/Wake'=>'+12:00,+12:00',
	'Pacific/Wallis'=>'+12:00,+12:00',
	'Pacific/Yap'=>'+10:00,+10:00',
	'UTC'=>'+00:00,+00:00'
	);
	public $currencies = array(
		'aed'=>'UAE Dirham',
		'afn'=>'Afghani',
		'all'=>'Lek',
		'amd'=>'Armenian Dram',
		'ang'=>'Netherlands Antillean Guilder',
		'aoa'=>'Kwanza',
		'ars'=>'Argentine Peso',
		'aud'=>'Australian Dollar',
		'awg'=>'Aruban Florin',
		'azn'=>'Azerbaijanian Manat',
		'bam'=>'Convertible Mark',
		'bbd'=>'Barbados Dollar',
		'bdt'=>'Taka',
		'bgn'=>'Bulgarian Lev',
		'bhd'=>'Bahraini Dinar',
		'bif'=>'Burundi Franc',
		'bmd'=>'Bermudian Dollar',
		'bnd'=>'Brunei Dollar',
		'bob'=>'Boliviano',
		'bov'=>'Mvdol',
		'brl'=>'Brazilian Real',
		'bsd'=>'Bahamian Dollar',
		'btn'=>'Ngultrum',
		'bwp'=>'Pula',
		'byr'=>'Belarussian Ruble',
		'bzd'=>'Belize Dollar',
		'cad'=>'Canadian Dollar',
		'cdf'=>'Congolese Franc',
		'che'=>'WIR Euro',
		'chf'=>'Swiss Franc',
		'chw'=>'WIR Franc',
		'clf'=>'Unidad de Fomento',
		'clp'=>'Chilean Peso',
		'cny'=>'Yuan Renminbi',
		'cop'=>'Colombian Peso',
		'cou'=>'Unidad de Valor Real',
		'crc'=>'Costa Rican Colon',
		'cuc'=>'Peso Convertible',
		'cup'=>'Cuban Peso',
		'cve'=>'Cabo Verde Escudo',
		'czk'=>'Czech Koruna',
		'djf'=>'Djibouti Franc',
		'dkk'=>'Danish Krone',
		'dop'=>'Dominican Peso',
		'dzd'=>'Algerian Dinar',
		'egp'=>'Egyptian Pound',
		'ern'=>'Nakfa',
		'etb'=>'Ethiopian Birr',
		'eur'=>'Euro',
		'fjd'=>'Fiji Dollar',
		'fkp'=>'Falkland Islands Pound',
		'gbp'=>'Pound Sterling',
		'gel'=>'Lari',
		'ghs'=>'Ghana Cedi',
		'gip'=>'Gibraltar Pound',
		'gmd'=>'Dalasi',
		'gnf'=>'Guinea Franc',
		'gtq'=>'Quetzal',
		'gyd'=>'Guyana Dollar',
		'hkd'=>'Hong Kong Dollar',
		'hnl'=>'Lempira',
		'hrk'=>'Kuna',
		'htg'=>'Gourde',
		'huf'=>'Forint',
		'idr'=>'Rupiah',
		'ils'=>'New Israeli Sheqel',
		'inr'=>'Indian Rupee',
		'iqd'=>'Iraqi Dinar',
		'irr'=>'Iranian Rial',
		'isk'=>'Iceland Krona',
		'jmd'=>'Jamaican Dollar',
		'jod'=>'Jordanian Dinar',
		'jpy'=>'Yen',
		'kes'=>'Kenyan Shilling',
		'kgs'=>'Som',
		'khr'=>'Riel',
		'kmf'=>'Comoro Franc',
		'kpw'=>'North Korean Won',
		'krw'=>'Won',
		'kwd'=>'Kuwaiti Dinar',
		'kyd'=>'Cayman Islands Dollar',
		'kzt'=>'Tenge',
		'lak'=>'Kip',
		'lbp'=>'Lebanese Pound',
		'lkr'=>'Sri Lanka Rupee',
		'lrd'=>'Liberian Dollar',
		'lsl'=>'Loti',
		'lyd'=>'Libyan Dinar',
		'mad'=>'Moroccan Dirham',
		'mdl'=>'Moldovan Leu',
		'mga'=>'Malagasy Ariary',
		'mkd'=>'Denar',
		'mmk'=>'Kyat',
		'mnt'=>'Tugrik',
		'mop'=>'Pataca',
		'mru'=>'Ouguiya',
		'mur'=>'Mauritius Rupee',
		'mvr'=>'Rufiyaa',
		'mwk'=>'Kwacha',
		'mxn'=>'Mexican Peso',
		'mxv'=>'Mexican Unidad de Inversion (UDI)',
		'myr'=>'Malaysian Ringgit',
		'mzn'=>'Mozambique Metical',
		'nad'=>'Namibia Dollar',
		'ngn'=>'Naira',
		'nio'=>'Cordoba Oro',
		'nok'=>'Norwegian Krone',
		'npr'=>'Nepalese Rupee',
		'nzd'=>'New Zealand Dollar',
		'omr'=>'Rial Omani',
		'pab'=>'Balboa',
		'pen'=>'Nuevo Sol',
		'pgk'=>'Kina',
		'php'=>'Philippine Peso',
		'pkr'=>'Pakistan Rupee',
		'pln'=>'Zloty',
		'pyg'=>'Guarani',
		'qar'=>'Qatari Rial',
		'ron'=>'Romanian Leu',
		'rsd'=>'Serbian Dinar',
		'rub'=>'Russian Ruble',
		'rwf'=>'Rwanda Franc',
		'sar'=>'Saudi Riyal',
		'sbd'=>'Solomon Islands Dollar',
		'scr'=>'Seychelles Rupee',
		'sdg'=>'Sudanese Pound',
		'sek'=>'Swedish Krona',
		'sgd'=>'Singapore Dollar',
		'shp'=>'Saint Helena Pound',
		'sll'=>'Leone',
		'sos'=>'Somali Shilling',
		'srd'=>'Surinam Dollar',
		'ssp'=>'South Sudanese Pound',
		'stn'=>'Dobra',
		'svc'=>'El Salvador Colon',
		'syp'=>'Syrian Pound',
		'szl'=>'Lilangeni',
		'thb'=>'Baht',
		'tjs'=>'Somoni',
		'tmt'=>'Turkmenistan New Manat',
		'tnd'=>'Tunisian Dinar',
		'top'=>'Pa’anga',
		'try'=>'Turkish Lira',
		'ttd'=>'Trinidad and Tobago Dollar',
		'twd'=>'New Taiwan Dollar',
		'tzs'=>'Tanzanian Shilling',
		'uah'=>'Hryvnia',
		'ugx'=>'Uganda Shilling',
		'usd'=>'US Dollar',
		'uyi'=>'Uruguay Peso en Unidades Indexadas',
		'uyu'=>'Peso Uruguayo',
		'uzs'=>'Uzbekistan Sum',
		'vef'=>'Bolivar',
		'vnd'=>'Dong',
		'vuv'=>'Vatu',
		'wst'=>'Tala',
		'xaf'=>'CFA Franc BEAC',
		'xcd'=>'East Caribbean Dollar',
		'xdr'=>'SDR (Special Drawing Right)',
		'xof'=>'CFA Franc BCEAO',
		'xpf'=>'CFP Franc',
		'xsu'=>'Sucre',
		'xua'=>'ADB Unit of Account',
		'yer'=>'Yemeni Rial',
		'zar'=>'Rand',
		'zmw'=>'Zambian Kwacha',
		'zwl'=>'Zimbabwe Dollar');
	public $mimetypes = array(
		'.3dm'=>'x-world/x-3dmf',
		'.3dmf'=>'x-world/x-3dmf',
		'.a'=>'application/octet-stream',
		'.aab'=>'application/x-authorware-bin',
		'.aam'=>'application/x-authorware-map',
		'.aas'=>'application/x-authorware-seg',
		'.abc'=>'text/vnd.abc',
		'.acgi'=>'text/html',
		'.afl'=>'video/animaflex',
		'.ai'=>'application/postscript',
		'.aif'=>'audio/aiff',
		'.aif'=>'audio/x-aiff',
		'.aifc'=>'audio/aiff',
		'.aifc'=>'audio/x-aiff',
		'.aiff'=>'audio/aiff',
		'.aiff'=>'audio/x-aiff',
		'.aim'=>'application/x-aim',
		'.aip'=>'text/x-audiosoft-intra',
		'.ani'=>'application/x-navi-animation',
		'.aos'=>'application/x-nokia-9000-communicator-add-on-software',
		'.aps'=>'application/mime',
		'.arc'=>'application/octet-stream',
		'.arj'=>'application/arj',
		'.arj'=>'application/octet-stream',
		'.art'=>'image/x-jg',
		'.asf'=>'video/x-ms-asf',
		'.asm'=>'text/x-asm',
		'.asp'=>'text/asp',
		'.asx'=>'application/x-mplayer2',
		'.asx'=>'video/x-ms-asf',
		'.asx'=>'video/x-ms-asf-plugin',
		'.au'=>'audio/basic',
		'.au'=>'audio/x-au',
		'.avi'=>'application/x-troff-msvideo',
		'.avi'=>'video/avi',
		'.avi'=>'video/msvideo',
		'.avi'=>'video/x-msvideo',
		'.avs'=>'video/avs-video',
		'.bcpio'=>'application/x-bcpio',
		'.bin'=>'application/mac-binary',
		'.bin'=>'application/macbinary',
		'.bin'=>'application/octet-stream',
		'.bin'=>'application/x-binary',
		'.bin'=>'application/x-macbinary',
		'.bm'=>'image/bmp',
		'.bmp'=>'image/bmp',
		'.bmp'=>'image/x-windows-bmp',
		'.boo'=>'application/book',
		'.book'=>'application/book',
		'.boz'=>'application/x-bzip2',
		'.bsh'=>'application/x-bsh',
		'.bz'=>'application/x-bzip',
		'.bz2'=>'application/x-bzip2',
		'.c'=>'text/plain',
		'.c'=>'text/x-c',
		'.cat'=>'application/vnd.ms-pki.seccat',
		'.cc'=>'text/plain',
		'.cc'=>'text/x-c',
		'.ccad'=>'application/clariscad',
		'.cco'=>'application/x-cocoa',
		'.cdf'=>'application/cdf',
		'.cdf'=>'application/x-cdf',
		'.cdf'=>'application/x-netcdf',
		'.cer'=>'application/pkix-cert',
		'.cer'=>'application/x-x509-ca-cert',
		'.cha'=>'application/x-chat',
		'.chat'=>'application/x-chat',
		'.class'=>'application/java',
		'.class'=>'application/java-byte-code',
		'.class'=>'application/x-java-class',
		'.com'=>'application/octet-stream',
		'.com'=>'text/plain',
		'.conf'=>'text/plain',
		'.cpio'=>'application/x-cpio',
		'.cpp'=>'text/x-c',
		'.cpt'=>'application/mac-compactpro',
		'.cpt'=>'application/x-compactpro',
		'.cpt'=>'application/x-cpt',
		'.crl'=>'application/pkcs-crl',
		'.crl'=>'application/pkix-crl',
		'.crt'=>'application/pkix-cert',
		'.crt'=>'application/x-x509-ca-cert',
		'.crt'=>'application/x-x509-user-cert',
		'.csh'=>'application/x-csh',
		'.csh'=>'text/x-script.csh',
		'.css'=>'application/x-pointplus',
		'.css'=>'text/css',
		'.cxx'=>'text/plain',
		'.dcr'=>'application/x-director',
		'.deepv'=>'application/x-deepv',
		'.def'=>'text/plain',
		'.der'=>'application/x-x509-ca-cert',
		'.dif'=>'video/x-dv',
		'.dir'=>'application/x-director',
		'.dl'=>'video/dl',
		'.dl'=>'video/x-dl',
		'.doc'=>'application/msword',
		'.dot'=>'application/msword',
		'.dp'=>'application/commonground',
		'.drw'=>'application/drafting',
		'.dump'=>'application/octet-stream',
		'.dv'=>'video/x-dv',
		'.dvi'=>'application/x-dvi',
		'.dwf'=>'drawing/x-dwf (old)',
		'.dwf'=>'model/vnd.dwf',
		'.dwg'=>'application/acad',
		'.dwg'=>'image/vnd.dwg',
		'.dwg'=>'image/x-dwg',
		'.dxf'=>'application/dxf',
		'.dxf'=>'image/vnd.dwg',
		'.dxf'=>'image/x-dwg',
		'.dxr'=>'application/x-director',
		'.el'=>'text/x-script.elisp',
		'.elc'=>'application/x-bytecode.elisp (compiled elisp)',
		'.elc'=>'application/x-elc',
		'.env'=>'application/x-envoy',
		'.eps'=>'application/postscript',
		'.es'=>'application/x-esrehber',
		'.etx'=>'text/x-setext',
		'.evy'=>'application/envoy',
		'.evy'=>'application/x-envoy',
		'.exe'=>'application/octet-stream',
		'.f'=>'text/plain',
		'.f'=>'text/x-fortran',
		'.f77'=>'text/x-fortran',
		'.f90'=>'text/plain',
		'.f90'=>'text/x-fortran',
		'.fdf'=>'application/vnd.fdf',
		'.fif'=>'application/fractals',
		'.fif'=>'image/fif',
		'.fli'=>'video/fli',
		'.fli'=>'video/x-fli',
		'.flo'=>'image/florian',
		'.flx'=>'text/vnd.fmi.flexstor',
		'.fmf'=>'video/x-atomic3d-feature',
		'.for'=>'text/plain',
		'.for'=>'text/x-fortran',
		'.fpx'=>'image/vnd.fpx',
		'.fpx'=>'image/vnd.net-fpx',
		'.frl'=>'application/freeloader',
		'.funk'=>'audio/make',
		'.g'=>'text/plain',
		'.g3'=>'image/g3fax',
		'.gif'=>'image/gif',
		'.gl'=>'video/gl',
		'.gl'=>'video/x-gl',
		'.gsd'=>'audio/x-gsm',
		'.gsm'=>'audio/x-gsm',
		'.gsp'=>'application/x-gsp',
		'.gss'=>'application/x-gss',
		'.gtar'=>'application/x-gtar',
		'.gz'=>'application/x-compressed',
		'.gz'=>'application/x-gzip',
		'.gzip'=>'application/x-gzip',
		'.gzip'=>'multipart/x-gzip',
		'.h'=>'text/plain',
		'.h'=>'text/x-h',
		'.hdf'=>'application/x-hdf',
		'.help'=>'application/x-helpfile',
		'.hgl'=>'application/vnd.hp-hpgl',
		'.hh'=>'text/plain',
		'.hh'=>'text/x-h',
		'.hlb'=>'text/x-script',
		'.hlp'=>'application/hlp',
		'.hlp'=>'application/x-helpfile',
		'.hlp'=>'application/x-winhelp',
		'.hpg'=>'application/vnd.hp-hpgl',
		'.hpgl'=>'application/vnd.hp-hpgl',
		'.hqx'=>'application/binhex',
		'.hqx'=>'application/binhex4',
		'.hqx'=>'application/mac-binhex',
		'.hqx'=>'application/mac-binhex40',
		'.hqx'=>'application/x-binhex40',
		'.hqx'=>'application/x-mac-binhex40',
		'.hta'=>'application/hta',
		'.htc'=>'text/x-component',
		'.htm'=>'text/html',
		'.html'=>'text/html',
		'.htmls'=>'text/html',
		'.htt'=>'text/webviewhtml',
		'.htx'=>'text/html',
		'.ice'=>'x-conference/x-cooltalk',
		'.ico'=>'image/x-icon',
		'.idc'=>'text/plain',
		'.ief'=>'image/ief',
		'.iefs'=>'image/ief',
		'.iges'=>'application/iges',
		'.iges'=>'model/iges',
		'.igs'=>'application/iges',
		'.igs'=>'model/iges',
		'.ima'=>'application/x-ima',
		'.imap'=>'application/x-httpd-imap',
		'.inf'=>'application/inf',
		'.ins'=>'application/x-internett-signup',
		'.ip'=>'application/x-ip2',
		'.isu'=>'video/x-isvideo',
		'.it'=>'audio/it',
		'.iv'=>'application/x-inventor',
		'.ivr'=>'i-world/i-vrml',
		'.ivy'=>'application/x-livescreen',
		'.jam'=>'audio/x-jam',
		'.jav'=>'text/plain',
		'.jav'=>'text/x-java-source',
		'.java'=>'text/plain',
		'.java'=>'text/x-java-source',
		'.jcm'=>'application/x-java-commerce',
		'.jfif'=>'image/jpeg',
		'.jfif'=>'image/pjpeg',
		'.jfi'=>'-tbnl	image/jpeg',
		'.jpe'=>'image/jpeg',
		'.jpe'=>'image/pjpeg',
		'.jpeg'=>'image/jpeg',
		'.jpeg'=>'image/pjpeg',
		'.jpg'=>'image/jpeg',
		'.jpg'=>'image/pjpeg',
		'.jps'=>'image/x-jps',
		'.js'=>'application/x-javascript',
		'.jut'=>'image/jutvision',
		'.kar'=>'audio/midi',
		'.kar'=>'music/x-karaoke',
		'.ksh'=>'application/x-ksh',
		'.ksh'=>'text/x-script.ksh',
		'.la'=>'audio/nspaudio',
		'.la'=>'audio/x-nspaudio',
		'.lam'=>'audio/x-liveaudio',
		'.latex'=>'application/x-latex',
		'.lha'=>'application/lha',
		'.lha'=>'application/octet-stream',
		'.lha'=>'application/x-lha',
		'.lhx'=>'application/octet-stream',
		'.list'=>'text/plain',
		'.lma'=>'audio/nspaudio',
		'.lma'=>'audio/x-nspaudio',
		'.log'=>'text/plain',
		'.lsp'=>'application/x-lisp',
		'.lsp'=>'text/x-script.lisp',
		'.lst'=>'text/plain',
		'.lsx'=>'text/x-la-asf',
		'.ltx'=>'application/x-latex',
		'.lzh'=>'application/octet-stream',
		'.lzh'=>'application/x-lzh',
		'.lzx'=>'application/lzx',
		'.lzx'=>'application/octet-stream',
		'.lzx'=>'application/x-lzx',
		'.m'=>'text/plain',
		'.m'=>'text/x-m',
		'.m1v'=>'video/mpeg',
		'.m2a'=>'audio/mpeg',
		'.m2v'=>'video/mpeg',
		'.m3u'=>'audio/x-mpequrl',
		'.man'=>'application/x-troff-man',
		'.map'=>'application/x-navimap',
		'.mar'=>'text/plain',
		'.mbd'=>'application/mbedlet',
		'.m'=>'$	application/x-magic-cap-package-1.0',
		'.mcd'=>'application/mcad',
		'.mcd'=>'application/x-mathcad',
		'.mcf'=>'image/vasa',
		'.mcf'=>'text/mcf',
		'.mcp'=>'application/netmc',
		'.me'=>'application/x-troff-me',
		'.mht'=>'message/rfc822',
		'.mhtml'=>'message/rfc822',
		'.mid'=>'application/x-midi',
		'.mid'=>'audio/midi',
		'.mid'=>'audio/x-mid',
		'.mid'=>'audio/x-midi',
		'.mid'=>'music/crescendo',
		'.mid'=>'x-music/x-midi',
		'.midi'=>'application/x-midi',
		'.midi'=>'audio/midi',
		'.midi'=>'audio/x-mid',
		'.midi'=>'audio/x-midi',
		'.midi'=>'music/crescendo',
		'.midi'=>'x-music/x-midi',
		'.mif'=>'application/x-frame',
		'.mif'=>'application/x-mif',
		'.mime'=>'message/rfc822',
		'.mime'=>'www/mime',
		'.mjf'=>'audio/x-vnd.audioexplosion.mjuicemediafile',
		'.mjpg'=>'video/x-motion-jpeg',
		'.mm'=>'application/base64',
		'.mm'=>'application/x-meme',
		'.mme'=>'application/base64',
		'.mod'=>'audio/mod',
		'.mod'=>'audio/x-mod',
		'.moov'=>'video/quicktime',
		'.mov'=>'video/quicktime',
		'.movie'=>'video/x-sgi-movie',
		'.mp2'=>'audio/mpeg',
		'.mp2'=>'audio/x-mpeg',
		'.mp2'=>'video/mpeg',
		'.mp2'=>'video/x-mpeg',
		'.mp2'=>'video/x-mpeq2a',
		'.mp3'=>'audio/mpeg3',
		'.mp3'=>'audio/x-mpeg-3',
		'.mp3'=>'video/mpeg',
		'.mp3'=>'video/x-mpeg',
		'.mpa'=>'audio/mpeg',
		'.mpa'=>'video/mpeg',
		'.mpc'=>'application/x-project',
		'.mpe'=>'video/mpeg',
		'.mpeg'=>'video/mpeg',
		'.mpg'=>'audio/mpeg',
		'.mpg'=>'video/mpeg',
		'.mpga'=>'audio/mpeg',
		'.mpp'=>'application/vnd.ms-project',
		'.mpt'=>'application/x-project',
		'.mpv'=>'application/x-project',
		'.mpx'=>'application/x-project',
		'.mrc'=>'application/marc',
		'.ms'=>'application/x-troff-ms',
		'.mv'=>'video/x-sgi-movie',
		'.my'=>'audio/make',
		'.mzz'=>'application/x-vnd.audioexplosion.mzz',
		'.nap'=>'image/naplps',
		'.naplps'=>'image/naplps',
		'.nc'=>'application/x-netcdf',
		'.ncm'=>'application/vnd.nokia.configuration-message',
		'.nif'=>'image/x-niff',
		'.niff'=>'image/x-niff',
		'.nix'=>'application/x-mix-transfer',
		'.nsc'=>'application/x-conference',
		'.nvd'=>'application/x-navidoc',
		'.o'=>'application/octet-stream',
		'.oda'=>'application/oda',
		'.omc'=>'application/x-omc',
		'.omcd'=>'application/x-omcdatamaker',
		'.omcr'=>'application/x-omcregerator',
		'.p'=>'text/x-pascal',
		'.p10'=>'application/pkcs10',
		'.p10'=>'application/x-pkcs10',
		'.p12'=>'application/pkcs-12',
		'.p12'=>'application/x-pkcs12',
		'.p7a'=>'application/x-pkcs7-signature',
		'.p7c'=>'application/pkcs7-mime',
		'.p7c'=>'application/x-pkcs7-mime',
		'.p7m'=>'application/pkcs7-mime',
		'.p7m'=>'application/x-pkcs7-mime',
		'.p7r'=>'application/x-pkcs7-certreqresp',
		'.p7s'=>'application/pkcs7-signature',
		'.part'=>'application/pro_eng',
		'.pas'=>'text/pascal',
		'.pbm'=>'image/x-portable-bitmap',
		'.pcl'=>'application/vnd.hp-pcl',
		'.pcl'=>'application/x-pcl',
		'.pct'=>'image/x-pict',
		'.pcx'=>'image/x-pcx',
		'.pdb'=>'chemical/x-pdb',
		'.pdf'=>'application/pdf',
		'.pfunk'=>'audio/make',
		'.pfunk'=>'audio/make.my.funk',
		'.pgm'=>'image/x-portable-graymap',
		'.pgm'=>'image/x-portable-greymap',
		'.pic'=>'image/pict',
		'.pict'=>'image/pict',
		'.pkg'=>'application/x-newton-compatible-pkg',
		'.pko'=>'application/vnd.ms-pki.pko',
		'.pl'=>'text/plain',
		'.pl'=>'text/x-script.perl',
		'.plx'=>'application/x-pixclscript',
		'.pm'=>'image/x-xpixmap',
		'.pm'=>'text/x-script.perl-module',
		'.pm4'=>'application/x-pagemaker',
		'.pm5'=>'application/x-pagemaker',
		'.png'=>'image/png',
		'.pnm'=>'application/x-portable-anymap',
		'.pnm'=>'image/x-portable-anymap',
		'.pot'=>'application/mspowerpoint',
		'.pot'=>'application/vnd.ms-powerpoint',
		'.pov'=>'model/x-pov',
		'.ppa'=>'application/vnd.ms-powerpoint',
		'.ppm'=>'image/x-portable-pixmap',
		'.pps'=>'application/mspowerpoint',
		'.pps'=>'application/vnd.ms-powerpoint',
		'.ppt'=>'application/mspowerpoint',
		'.ppt'=>'application/powerpoint',
		'.ppt'=>'application/vnd.ms-powerpoint',
		'.ppt'=>'application/x-mspowerpoint',
		'.ppz'=>'application/mspowerpoint',
		'.pre'=>'application/x-freelance',
		'.prt'=>'application/pro_eng',
		'.ps'=>'application/postscript',
		'.psd'=>'application/octet-stream',
		'.pvu'=>'paleovu/x-pv',
		'.pwz'=>'application/vnd.ms-powerpoint',
		'.py'=>'text/x-script.phyton',
		'.pyc'=>'applicaiton/x-bytecode.python',
		'.qcp'=>'audio/vnd.qcelp',
		'.qd3'=>'x-world/x-3dmf',
		'.qd3d'=>'x-world/x-3dmf',
		'.qif'=>'image/x-quicktime',
		'.qt'=>'video/quicktime',
		'.qtc'=>'video/x-qtc',
		'.qti'=>'image/x-quicktime',
		'.qtif'=>'image/x-quicktime',
		'.ra'=>'audio/x-pn-realaudio',
		'.ra'=>'audio/x-pn-realaudio-plugin',
		'.ra'=>'audio/x-realaudio',
		'.ram'=>'audio/x-pn-realaudio',
		'.ras'=>'application/x-cmu-raster',
		'.ras'=>'image/cmu-raster',
		'.ras'=>'image/x-cmu-raster',
		'.rast'=>'image/cmu-raster',
		'.rexx'=>'text/x-script.rexx',
		'.rf'=>'image/vnd.rn-realflash',
		'.rgb'=>'image/x-rgb',
		'.rm'=>'application/vnd.rn-realmedia',
		'.rm'=>'audio/x-pn-realaudio',
		'.rmi'=>'audio/mid',
		'.rmm'=>'audio/x-pn-realaudio',
		'.rmp'=>'audio/x-pn-realaudio',
		'.rmp'=>'audio/x-pn-realaudio-plugin',
		'.rng'=>'application/ringing-tones',
		'.rng'=>'application/vnd.nokia.ringing-tone',
		'.rnx'=>'application/vnd.rn-realplayer',
		'.roff'=>'application/x-troff',
		'.rp'=>'image/vnd.rn-realpix',
		'.rpm'=>'audio/x-pn-realaudio-plugin',
		'.rt'=>'text/richtext',
		'.rt'=>'text/vnd.rn-realtext',
		'.rtf'=>'application/rtf',
		'.rtf'=>'application/x-rtf',
		'.rtf'=>'text/richtext',
		'.rtx'=>'application/rtf',
		'.rtx'=>'text/richtext',
		'.rv'=>'video/vnd.rn-realvideo',
		'.s'=>'text/x-asm',
		'.s3m'=>'audio/s3m',
		'.saveme'=>'application/octet-stream',
		'.sbk'=>'application/x-tbook',
		'.scm'=>'application/x-lotusscreencam',
		'.scm'=>'text/x-script.guile',
		'.scm'=>'text/x-script.scheme',
		'.scm'=>'video/x-scm',
		'.sdml'=>'text/plain',
		'.sdp'=>'application/sdp',
		'.sdp'=>'application/x-sdp',
		'.sdr'=>'application/sounder',
		'.sea'=>'application/sea',
		'.sea'=>'application/x-sea',
		'.set'=>'application/set',
		'.sgm'=>'text/sgml',
		'.sgm'=>'text/x-sgml',
		'.sgml'=>'text/sgml',
		'.sgml'=>'text/x-sgml',
		'.sh'=>'application/x-bsh',
		'.sh'=>'application/x-sh',
		'.sh'=>'application/x-shar',
		'.sh'=>'text/x-script.sh',
		'.shar'=>'application/x-bsh',
		'.shar'=>'application/x-shar',
		'.shtml'=>'text/html',
		'.shtml'=>'text/x-server-parsed-html',
		'.sid'=>'audio/x-psid',
		'.sit'=>'application/x-sit',
		'.sit'=>'application/x-stuffit',
		'.skd'=>'application/x-koan',
		'.skm'=>'application/x-koan',
		'.skp'=>'application/x-koan',
		'.skt'=>'application/x-koan',
		'.sl'=>'application/x-seelogo',
		'.smi'=>'application/smil',
		'.smil'=>'application/smil',
		'.snd'=>'audio/basic',
		'.snd'=>'audio/x-adpcm',
		'.sol'=>'application/solids',
		'.spc'=>'application/x-pkcs7-certificates',
		'.spc'=>'text/x-speech',
		'.spl'=>'application/futuresplash',
		'.spr'=>'application/x-sprite',
		'.sprite'=>'application/x-sprite',
		'.src'=>'application/x-wais-source',
		'.ssi'=>'text/x-server-parsed-html',
		'.ssm'=>'application/streamingmedia',
		'.sst'=>'application/vnd.ms-pki.certstore',
		'.step'=>'application/step',
		'.stl'=>'application/sla',
		'.stl'=>'application/vnd.ms-pki.stl',
		'.stl'=>'application/x-navistyle',
		'.stp'=>'application/step',
		'.sv4cpio'=>'application/x-sv4cpio',
		'.sv4crc'=>'application/x-sv4crc',
		'.svf'=>'image/vnd.dwg',
		'.svf'=>'image/x-dwg',
		'.svr'=>'application/x-world',
		'.svr'=>'x-world/x-svr',
		'.swf'=>'application/x-shockwave-flash',
		'.t'=>'application/x-troff',
		'.talk'=>'text/x-speech',
		'.tar'=>'application/x-tar',
		'.tbk'=>'application/toolbook',
		'.tbk'=>'application/x-tbook',
		'.tcl'=>'application/x-tcl',
		'.tcl'=>'text/x-script.tcl',
		'.tcsh'=>'text/x-script.tcsh',
		'.tex'=>'application/x-tex',
		'.texi'=>'application/x-texinfo',
		'.texinfo'=>'application/x-texinfo',
		'.text'=>'application/plain',
		'.text'=>'text/plain',
		'.tgz'=>'application/gnutar',
		'.tgz'=>'application/x-compressed',
		'.tif'=>'image/tiff',
		'.tif'=>'image/x-tiff',
		'.tiff'=>'image/tiff',
		'.tiff'=>'image/x-tiff',
		'.tr'=>'application/x-troff',
		'.tsi'=>'audio/tsp-audio',
		'.tsp'=>'application/dsptype',
		'.tsp'=>'audio/tsplayer',
		'.tsv'=>'text/tab-separated-values',
		'.turbot'=>'image/florian',
		'.txt'=>'text/plain',
		'.uil'=>'text/x-uil',
		'.uni'=>'text/uri-list',
		'.unis'=>'text/uri-list',
		'.unv'=>'application/i-deas',
		'.uri'=>'text/uri-list',
		'.uris'=>'text/uri-list',
		'.ustar'=>'application/x-ustar',
		'.ustar'=>'multipart/x-ustar',
		'.uu'=>'application/octet-stream',
		'.uu'=>'text/x-uuencode',
		'.uue'=>'text/x-uuencode',
		'.vcd'=>'application/x-cdlink',
		'.vcs'=>'text/x-vcalendar',
		'.vda'=>'application/vda',
		'.vdo'=>'video/vdo',
		'.vew'=>'application/groupwise',
		'.viv'=>'video/vivo',
		'.viv'=>'video/vnd.vivo',
		'.vivo'=>'video/vivo',
		'.vivo'=>'video/vnd.vivo',
		'.vmd'=>'application/vocaltec-media-desc',
		'.vmf'=>'application/vocaltec-media-file',
		'.voc'=>'audio/voc',
		'.voc'=>'audio/x-voc',
		'.vos'=>'video/vosaic',
		'.vox'=>'audio/voxware',
		'.vqe'=>'audio/x-twinvq-plugin',
		'.vqf'=>'audio/x-twinvq',
		'.vql'=>'audio/x-twinvq-plugin',
		'.vrml'=>'application/x-vrml',
		'.vrml'=>'model/vrml',
		'.vrml'=>'x-world/x-vrml',
		'.vrt'=>'x-world/x-vrt',
		'.vsd'=>'application/x-visio',
		'.vst'=>'application/x-visio',
		'.vsw'=>'application/x-visio',
		'.w60'=>'application/wordperfect6.0',
		'.w61'=>'application/wordperfect6.1',
		'.w6w'=>'application/msword',
		'.wav'=>'audio/wav',
		'.wav'=>'audio/x-wav',
		'.wb1'=>'application/x-qpro',
		'.wbmp'=>'image/vnd.wap.wbmp',
		'.web'=>'application/vnd.xara',
		'.wiz'=>'application/msword',
		'.wk1'=>'application/x-123',
		'.wmf'=>'windows/metafile',
		'.wml'=>'text/vnd.wap.wml',
		'.wmlc'=>'application/vnd.wap.wmlc',
		'.wmls'=>'text/vnd.wap.wmlscript',
		'.wmlsc'=>'application/vnd.wap.wmlscriptc',
		'.word'=>'application/msword',
		'.wp'=>'application/wordperfect',
		'.wp5'=>'application/wordperfect',
		'.wp5'=>'application/wordperfect6.0',
		'.wp6'=>'application/wordperfect',
		'.wpd'=>'application/wordperfect',
		'.wpd'=>'application/x-wpwin',
		'.wq1'=>'application/x-lotus',
		'.wri'=>'application/mswrite',
		'.wri'=>'application/x-wri',
		'.wrl'=>'application/x-world',
		'.wrl'=>'model/vrml',
		'.wrl'=>'x-world/x-vrml',
		'.wrz'=>'model/vrml',
		'.wrz'=>'x-world/x-vrml',
		'.wsc'=>'text/scriplet',
		'.wsrc'=>'application/x-wais-source',
		'.wtk'=>'application/x-wintalk',
		'.xbm'=>'image/x-xbitmap',
		'.xbm'=>'image/x-xbm',
		'.xbm'=>'image/xbm',
		'.xdr'=>'video/x-amt-demorun',
		'.xgz'=>'xgl/drawing',
		'.xif'=>'image/vnd.xiff',
		'.xl'=>'application/excel',
		'.xla'=>'application/excel',
		'.xla'=>'application/x-excel',
		'.xla'=>'application/x-msexcel',
		'.xlb'=>'application/excel',
		'.xlb'=>'application/vnd.ms-excel',
		'.xlb'=>'application/x-excel',
		'.xlc'=>'application/excel',
		'.xlc'=>'application/vnd.ms-excel',
		'.xlc'=>'application/x-excel',
		'.xld'=>'application/excel',
		'.xld'=>'application/x-excel',
		'.xlk'=>'application/excel',
		'.xlk'=>'application/x-excel',
		'.xll'=>'application/excel',
		'.xll'=>'application/vnd.ms-excel',
		'.xll'=>'application/x-excel',
		'.xlm'=>'application/excel',
		'.xlm'=>'application/vnd.ms-excel',
		'.xlm'=>'application/x-excel',
		'.xls'=>'application/excel',
		'.xls'=>'application/vnd.ms-excel',
		'.xls'=>'application/x-excel',
		'.xls'=>'application/x-msexcel',
		'.xlt'=>'application/excel',
		'.xlt'=>'application/x-excel',
		'.xlv'=>'application/excel',
		'.xlv'=>'application/x-excel',
		'.xlw'=>'application/excel',
		'.xlw'=>'application/vnd.ms-excel',
		'.xlw'=>'application/x-excel',
		'.xlw'=>'application/x-msexcel',
		'.xm'=>'audio/xm',
		'.xml'=>'application/xml',
		'.xml'=>'text/xml',
		'.xmz'=>'xgl/movie',
		'.xpix'=>'application/x-vnd.ls-xpix',
		'.xpm'=>'image/x-xpixmap',
		'.xpm'=>'image/xpm',
		'.'=>'-png	image/png',
		'.xsr'=>'video/x-amt-showrun',
		'.xwd'=>'image/x-xwd',
		'.xwd'=>'image/x-xwindowdump',
		'.xyz'=>'chemical/x-pdb',
		'.z'=>'application/x-compress',
		'.z'=>'application/x-compressed',
		'.zip'=>'application/x-compressed',
		'.zip'=>'application/x-zip-compressed',
		'.zip'=>'application/zip',
		'.zip'=>'multipart/x-zip',
		'.zoo'=>'application/octet-stream',
		'.zsh'=>'text/x-script.zsh'
		);
	public $ColorNames = array(
		"AliceBlue ",
		"AntiqueWhite ",
		"Aqua ",
		"Aquamarine ",
		"Azure ",
		"Beige ",
		"Bisque ",
		"Black ",
		"BlanchedAlmond ",
		"Blue ",
		"BlueViolet ",
		"Brown ",
		"BurlyWood ",
		"CadetBlue ",
		"Chartreuse ",
		"Chocolate ",
		"Coral ",
		"CornflowerBlue ",
		"Cornsilk ",
		"Crimson ",
		"Cyan ",
		"DarkBlue ",
		"DarkCyan ",
		"DarkGoldenRod ",
		"DarkGray ",
		"DarkGrey ",
		"DarkGreen ",
		"DarkKhaki ",
		"DarkMagenta ",
		"DarkOliveGreen ",
		"DarkOrange ",
		"DarkOrchid ",
		"DarkRed ",
		"DarkSalmon ",
		"DarkSeaGreen ",
		"DarkSlateBlue ",
		"DarkSlateGray ",
		"DarkSlateGrey ",
		"DarkTurquoise ",
		"DarkViolet ",
		"DeepPink ",
		"DeepSkyBlue ",
		"DimGray ",
		"DimGrey ",
		"DodgerBlue ",
		"FireBrick ",
		"FloralWhite ",
		"ForestGreen ",
		"Fuchsia ",
		"Gainsboro ",
		"GhostWhite ",
		"Gold ",
		"GoldenRod ",
		"Gray ",
		"Grey ",
		"Green ",
		"GreenYellow ",
		"HoneyDew ",
		"HotPink ",
		"IndianRed  ",
		"Indigo  ",
		"Ivory ",
		"Khaki ",
		"Lavender ",
		"LavenderBlush ",
		"LawnGreen ",
		"LemonChiffon ",
		"LightBlue ",
		"LightCoral ",
		"LightCyan ",
		"LightGoldenRodYellow ",
		"LightGray ",
		"LightGrey ",
		"LightGreen ",
		"LightPink ",
		"LightSalmon ",
		"LightSeaGreen ",
		"LightSkyBlue ",
		"LightSlateGray ",
		"LightSlateGrey ",
		"LightSteelBlue ",
		"LightYellow ",
		"Lime ",
		"LimeGreen ",
		"Linen ",
		"Magenta ",
		"Maroon ",
		"MediumAquaMarine ",
		"MediumBlue ",
		"MediumOrchid ",
		"MediumPurple ",
		"MediumSeaGreen ",
		"MediumSlateBlue ",
		"MediumSpringGreen ",
		"MediumTurquoise ",
		"MediumVioletRed ",
		"MidnightBlue ",
		"MintCream ",
		"MistyRose ",
		"Moccasin ",
		"NavajoWhite ",
		"Navy ",
		"OldLace ",
		"Olive ",
		"OliveDrab ",
		"Orange ",
		"OrangeRed ",
		"Orchid ",
		"PaleGoldenRod ",
		"PaleGreen ",
		"PaleTurquoise ",
		"PaleVioletRed ",
		"PapayaWhip ",
		"PeachPuff ",
		"Peru ",
		"Pink ",
		"Plum ",
		"PowderBlue ",
		"Purple ",
		"RebeccaPurple ",
		"Red ",
		"RosyBrown ",
		"RoyalBlue ",
		"SaddleBrown ",
		"Salmon ",
		"SandyBrown ",
		"SeaGreen ",
		"SeaShell ",
		"Sienna ",
		"Silver ",
		"SkyBlue ",
		"SlateBlue ",
		"SlateGray ",
		"SlateGrey ",
		"Snow ",
		"SpringGreen ",
		"SteelBlue ",
		"Tan ",
		"Teal ",
		"Thistle ",
		"Tomato ",
		"Turquoise ",
		"Violet ",
		"Wheat ",
		"White ",
		"WhiteSmoke ",
		"Yellow ",
		"YellowGreen "
	);
}